version: '3'

services:

  pi-hole:
    image: ${PH_IMAGE}
    container_name: pi-hole
    networks:
      - nginx-proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '880:80/tcp'
      - '8443:443/tcp'
    cap_add:
      - NET_ADMIN
    environment:
      TZ: Asia/Shanghai
      VIRTUAL_HOST: ${PH_DOMAINS}
      WEBPASSWORD: ${PH_WEB_PASSWORD}
      DNS1: ${PH_UPSTREAM_DNS1}
      DNS2: ${PH_UPSTREAM_DNS2}
    volumes:
      - './config/conf:/etc/pihole'
      - './config/dnsmasq.d:/etc/dnsmasq.d'
      - './config/adlists.list:/etc/pihole/adlists.list'
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
