apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared-ds
  namespace: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app: cloudflare-tunnel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      tolerations:
        - key: node-role.kubernetes.io/controller-plane
          effect: NoSchedule
          operator: Exists
      terminationGracePeriodSeconds: 30
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2023.2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token
          args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:8080
            - run
          ports:
            - containerPort: 8080
              name: http-metrics
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 6
